INSERT INTO app_properties (name, value, type, description) VALUES
  ('server.port',                    '8080',                                                                              'INTEGER', 'HTTP server port'),
  ('application.name',               'Jakarta EE Servlet Application',                                                   'STRING',  'Application display name'),
  ('application.version',            '1.0',                                                                               'STRING',  'Application version'),
  ('application.environment',        'dev',                                                                               'STRING',  'Runtime environment: dev or prod'),
  ('upload.maxFileSize',             '10485760',                                                                          'LONG',    'Maximum upload file size in bytes (10 MB)'),
  ('upload.maxRequestSize',          '52428800',                                                                          'LONG',    'Maximum multipart request size in bytes (50 MB)'),
  ('upload.fileSizeThreshold',       '1048576',                                                                           'INTEGER', 'File size threshold before writing to disk (1 MB)'),
  ('upload.tempDirectory',           '',                                                                                  'STRING',  'Temporary directory for uploads; empty means java.io.tmpdir'),
  ('threadPool.maxThreads',          '200',                                                                               'INTEGER', 'Maximum Tomcat thread pool size'),
  ('threadPool.minSpareThreads',     '10',                                                                                'INTEGER', 'Minimum spare Tomcat threads'),
  ('threadPool.acceptCount',         '100',                                                                               'INTEGER', 'Tomcat accept queue size'),
  ('threadPool.connectionTimeout',   '20000',                                                                             'INTEGER', 'Tomcat connection timeout in milliseconds'),
  ('script.timeout',                 '5000',                                                                              'INTEGER', 'JavaScript execution timeout in milliseconds'),
  ('script.maxMemory',               '52428800',                                                                          'LONG',    'Max JVM heap growth per script execution in bytes (50 MB)'),
  ('script.optimizationLevel',       '-1',                                                                                'INTEGER', 'Rhino optimisation level: -1 = interpreted'),
  ('script.instructionThreshold',    '10000',                                                                             'INTEGER', 'Instruction count between timeout/memory checks'),
  ('modules.directory',              'modules',                                                                           'STRING',  'Directory for JavaScript modules'),
  ('modules.maxFileSize',            '1048576',                                                                           'LONG',    'Maximum module file size in bytes (1 MB)'),
  ('storage.type',                   'database',                                                                          'STRING',  'Attachment storage backend: filesystem or database'),
  ('storage.chunkSize',              '1048576',                                                                           'INTEGER', 'Streaming chunk size in bytes (1 MB)'),
  ('storage.filesystem.path',        'attachments',                                                                       'STRING',  'Base directory for filesystem attachment storage'),
  ('storage.s3.bucket',              '',                                                                                  'STRING',  'S3 bucket name for attachment storage'),
  ('storage.s3.region',              'us-east-1',                                                                         'STRING',  'S3 region for attachment storage'),
  ('storage.database.table',         'attachment_chunks',                                                                 'STRING',  'Table name used for database attachment storage'),
  ('logging.level',                  'INFO',                                                                              'STRING',  'Root log level: TRACE DEBUG INFO WARN ERROR'),
  ('logging.fileEnabled',            'true',                                                                              'BOOLEAN', 'Enable file-based log appender'),
  ('logging.filePath',               'logs/application.log',                                                              'STRING',  'Log file path'),
  ('logging.fileMaxSize',            '10MB',                                                                              'STRING',  'Maximum log file size before rolling'),
  ('logging.fileMaxHistory',         '30',                                                                                'INTEGER', 'Number of archived log files to keep'),
  ('logging.fileTotalSizeCap',       '1GB',                                                                               'STRING',  'Total size cap for all log files'),
  ('logging.consolePattern',         '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n',              'STRING',  'Logback pattern for console output'),
  ('logging.filePattern',            '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n',              'STRING',  'Logback pattern for file output')
ON CONFLICT (name) DO NOTHING;
